name: Terraform Apply on PR Approval
on:
  pull_request:
    types:
        - closed
    branches:
          - main    
env:
  TF_LOG: INFO
  TF_INPUT: false
  
jobs: 
  check-code:
    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to vnet for the config files
    defaults:
        run:
          shell: bash
          working-directory: ./environments/us-east-1

          

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration.
    - name: Install Terraform
      run: |
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform
          
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # replace with your AWS region    
    
    - name: Add profile credentials to ~/.aws/credentials
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PROFILE: ${{secrets.PROFILE}}
      run: |
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile $PROFILE 
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile $PROFILE     

    # - name: Terraform Init
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     KMS_KEY_ID: ${{secrets.KMS_KEY_ID}}
    #     BUCKET_NAME: ${{secrets.BUCKET_NAME}}
    #     DYNAMO_TABLE: ${{secrets.DYNAMO_TABLE}}
    #     FILE_KEY: ${{secrets.FILE_KEY}}
    #     PROFILE: ${{secrets.PROFILE}}
    #   run: terraform init -backend-config="kms_key_id=$KMS_KEY_ID" -backend-config="bucket=$BUCKET_NAME" -backend-config="dynamodb_table=$DYNAMO_TABLE" -backend-config="key=$FILE_KEY" -backend-config="profile=$PROFILE"
    
    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform plan 
      
    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve -lock=false